# Generated by Django 5.1 on 2024-08-08 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuralProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento_tipo", models.CharField(max_length=4)),
                ("documento_numero", models.CharField(max_length=14, unique=True)),
                ("nome_produtor", models.CharField(max_length=100)),
                ("nome_fazenda", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                (
                    "area_total_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "area_agricultavel_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "area_vegetacao_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("culturas_plantadas", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["documento_numero"], name="documento_numero_idx"
                    )
                ],
            },
        ),
    ]
