# Generated by Django 5.1 on 2024-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rural_producer", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ruralproducer",
            index=models.Index(
                fields=["culturas_plantadas"], name="culturas_plantadas_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruralproducer",
            index=models.Index(fields=["estado"], name="estado_idx"),
        ),
    ]
